name: 'nextjs-particlex-theme/generate-sitemap'
description: '一个 专门 用于 particlex 主题的 Github Action，用于生成 sitemap。'
branding:
  icon: map
  color: 'blue'
inputs:
  source-path:
    description: '仓库的路径，在运行后将会提交一个 sitemap 缓存文件到你的仓库里'
    required: true
    default: 'datasource'
  output-path:
    description: 'HTML 输出路径'
    required: true
    default: 'nextjs-particlex-theme/out'
  pages-path:
    description: 'Markdown 保存路径，相对于 `source-path` 的路径'
    required: true
    default: 'source'
  sitemap-cache-file:
    description: 'sitemap 缓存文件放在哪里，相对于 `source-path` 的路径'
    required: true
    default: 'sitemap-cache.json'
  web-base-path:
    description: '博客访问路径'
    required: true
  commit-message:
    description: '自定义提交信息'
    default: 'Update sitemap-cache.json'
runs:
  using: 'node20'
  main: 'dist/bundle.js'
